export * from './auth.schema'
export * from './calendar.schema'
export * from './classes.schema'
export * from './frequencies.schema'
export * from './school.schema'
export * from './students.schema'
export * from './user.schema'
