export * from './auth.interfaces'
export * from './calendar.interfaces'
export * from './classes.interfaces'
export * from './frequencies.interfaces'
export * from './global.interfaces'
export * from './schools.interfaces'
export * from './students.interfaces'
export * from './users.interfaces'
